### ISSUE TITLE
无法识别，调试代码返回的结果都是空串

### ISSUE THREAD

**Issue by geekyouth** [AnyListen/tools-ocr#1]
sogouWebOcr
sogouMobileOcr

两个方法调用结果都是空串

![image](https://user-images.githubusercontent.com/12899262/54897553-e232ff80-4f03-11e9-9134-c2e4339bc8a8.png)

![image](https://user-images.githubusercontent.com/12899262/54897574-f676fc80-4f03-11e9-9704-115cb0e2321b.png)

**Comment by AnyListen** [comment]
如果是 MAC 需要赋予截图的权限；
你可以调试查看一下发送的图片是否有内容；
个人调试一切都正常

**Comment by geekyouth** [comment]
我传递的是byte[] 字节数组，没有截图

**Comment by AnyListen** [comment]
你的意思是你讲图片转为 byte[] 然后调用了上述的方法么？
那有一个前提是图片必须是 jpeg/jpg 的格式，否则也是无法正常解析的

**Comment by AnyListen** [comment]
请更新到最新代码，并且保证图片格式为 jpg，然后进行重试
