### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lazymonkeyH** [AnyListen/tools-ocr#11]
win10,64位，安装到最后，系统提示：
failed to find library
\bin\server\jvm
点击确定，继续报错：
failed to locate JNI_CreateJavaVM
点击确定，继续报错：
failed to launch JVM

**Comment by AnyListen** [comment]
使用的完整版，还是精简版？

**Comment by lazymonkeyH** [comment]
完整版

**Comment by AnyListen** [comment]
这个是 JDK 8U152 的 BUG；在 JDK 8U162 已修复；
新版本会打包 JDK 8U212，到时候请验证一下

**Comment by AnyListen** [comment]
已更新，请验证

**Comment by WingGao** [comment]
> 这个是 JDK 8U152 的 BUG；在 JDK 8U162 已修复；
> 新版本会打包 JDK 8U212，到时候请验证一下

可以解决
