### ISSUE TITLE
识别英文的时候最后一个单词会和下一行的单词连在一起

### ISSUE THREAD

**Issue by weishx** [AnyListen/tools-ocr#15]
例如这个图
![image](https://user-images.githubusercontent.com/10293644/59893778-99aab580-9410-11e9-87e6-d75127161e09.png)
识别出来后是这样的，例如其中的make和it会连成一个单词
【派生】accuracy n.精确性，正确度
inaccurate a.不准确的，模糊的
  真题 Inaccurate or indefinite words may makeit difficult for the listener to understand themessage which is being transmitted to him.不准确的或不确定的语言会使听者很难理解传达给他的信息。
![image](https://user-images.githubusercontent.com/10293644/59893831-c8c12700-9410-11e9-9b0c-52606764ca31.png)

**Comment by AnyListen** [comment]
新版本已修复

**Comment by AnyListen** [comment]
已更新，请验证
