### ISSUE TITLE
发现一个新的ocr轮子

### ISSUE THREAD

**Issue by mromm** [AnyListen/tools-ocr#20]
https://github.com/miaomiaosoft/PandaOCR

**Comment by kli2013** [comment]
试用过,配置里加了api key也不能使用api接口
效果很差
还是以前的天若好用

**Comment by miaomiaosoft** [comment]
> 试用过,配置里加了api key也不能使用api接口
> 效果很差
> 还是以前的天若好用

哎，不好使也没人反馈，我自己又用不到全部的接口，API接口又多算起来差不多十个左右，没法一个个去严格测试，而且有的接口官方是自己会更新换代
