### ISSUE TITLE
安装后打开报错是怎么回事?

### ISSUE THREAD

**Issue by dnknn** [AnyListen/tools-ocr#22]
下载安装的是treehole-1.2.0-with-jre.exe完整版的, 然后打开就报错了,如下两图.
系统是Win10 64位.
请问怎么办?
![1](https://user-images.githubusercontent.com/10995302/62264241-b85d8c80-b451-11e9-990a-f25009218d43.png)
![2](https://user-images.githubusercontent.com/10995302/62264242-b85d8c80-b451-11e9-8a78-3bb9a72fdf70.png)

**Comment by hemiaoio** [comment]
请下载带JRE版本的。

**Comment by dnknn** [comment]
@hemiaoio > 请下载带JRE版本的。
请问为什么不认真看清下, 我还特意开头就说了是下载安装的是treehole-1.2.0-with-jre.exe完整版的,
-jre.exe完整版的.
安装文件有52.6M.
就是带JRE版本的啊, 也报错打不开

**Comment by hemiaoio** [comment]
不好意思，审题不清，没注意你已经下载的是JRE版的了

**Comment by Z-fly** [comment]
> 不好意思，审题不清，没注意你已经下载的是JRE版的了

我也遇到这样的情况，怎么解决

**Comment by AnyListen** [comment]
@dnknn 没看到图片

**Comment by AnyListen** [comment]
安装的时候不要放在中文路径下即可
