### ISSUE TITLE
安装后，无法启动

### ISSUE THREAD

**Issue by gaspolymerase** [AnyListen/tools-ocr#28]
![图片](https://user-images.githubusercontent.com/52350568/66177386-d8007380-e693-11e9-8e38-33afdd1ce03a.png)
![图片](https://user-images.githubusercontent.com/52350568/66177393-de8eeb00-e693-11e9-84a6-ced8a954b2ee.png)

**Comment by AnyListen** [comment]
安装路径不要有中文符合
