### ISSUE TITLE
不能识别竖立的文字

### ISSUE THREAD

**Issue by 123456ds** [AnyListen/tools-ocr#29]
例图[url=https://sm.ms/image/wkd9lJFhb36iqys][img]https://i.loli.net/2019/10/12/wkd9lJFhb36iqys.png[/img][/url]

**Comment by 123456ds** [comment]
https://i.loli.net/2019/10/12/wkd9lJFhb36iqys.png

**Comment by AnyListen** [comment]
暂不支持，推荐使用天若OCR
