### ISSUE TITLE
截取图片的位置不对

### ISSUE THREAD

**Issue by guopan** [AnyListen/tools-ocr#3]
我是主屏4K分辨率，副屏1920*1080，截屏在主屏上选取一个框，结果识别结果不是我选的区域，而是上面的某个区域。。。

**Comment by AnyListen** [comment]
这个有机会试一下，目前还没有硬件设备，无法测试

**Comment by AnyListen** [comment]
多显示器截图 BUG 已经修复 ，请等待 1.2.0 版本发布
