### ISSUE TITLE
如何打包成exe文件

### ISSUE THREAD

**Issue by litongjava** [AnyListen/tools-ocr#31]
下载后导入到eclise中如,可以生成jar包,但是没有办法运行
![image](https://user-images.githubusercontent.com/31761981/69739957-8516da00-1173-11ea-8104-a8a57a699231.png)
1.生成jjar包之后如何运行
2.生成jjar包之后打包成exe文件

**Comment by AnyListen** [comment]
打包使用的是：https://github.com/javafx-maven-plugin/javafx-maven-plugin
打包命令：`mvn jfx:native`
前提是确保在windows平台，且pom.xml配置javafx-maven-plugin的<bundler>exe</bundler>
