### ISSUE TITLE
第二次打开时出现报错，打不开

### ISSUE THREAD

**Issue by xufeifan1997** [AnyListen/tools-ocr#34]
![image](https://user-images.githubusercontent.com/39561218/75442692-fa748f80-599a-11ea-90ab-a43289fd93a9.png)
![image](https://user-images.githubusercontent.com/39561218/75442761-19732180-599b-11ea-9c78-45a6c1cccb9c.png)

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
