### ISSUE TITLE
版本安装报错

### ISSUE THREAD

**Issue by idaijunming** [AnyListen/tools-ocr#35]
带JRE与不带JRE的都试过了，报一样的错
![image](https://user-images.githubusercontent.com/40954491/76831087-9d654e80-6861-11ea-9af4-3febfc5c021c.png)

**Comment by junqilu** [comment]
同样有这个问题

**Comment by CYFchenyifei** [comment]
同问

**Comment by CYFchenyifei** [comment]
我找到方法了，用中文路径，详情可以翻阅之前closed的issue

**Comment by idaijunming** [comment]
这个错误是没有权限在桌面创建快捷菜单，我感觉报这个错不影响使用
