### ISSUE TITLE
windows 7 安装后无反应 

### ISSUE THREAD

**Issue by jiuweiljp** [AnyListen/tools-ocr#38]
win7：ghost的win7，Microsoft Windows [版本 6.1.7601]
树洞：jre版本和普通版本都不行（安装java jdk8u202x64 ）
现象：安装后在任务管理器-进程 中能看见树洞的进程，但没有软件界面显示。
不知道缺什么原因？

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
