### ISSUE TITLE
识别完后没显示结果，程序退出

### ISSUE THREAD

**Issue by hliang** [AnyListen/tools-ocr#40]
在Eclipse里编译运行，选择图片文件，出现“正在识别图片，请稍等.....”的提示，过一会后树洞就退出了。debug了一下，识别结果应该是获取到了，接着`restore`运行完，然而界面窗口没有恢复。不知为何程序终止了。

如果我把`recImage()`里的`MainFm.stage.close()`注释掉后就不会退出了。
https://github.com/AnyListen/tools-ocr/blob/ae49a2d0fdefd271d1b980a93d74269a3c009b9d/src/main/java/com/luooqi/ocr/MainFm.java#L181-L187

环境:
Eclipse Version: 2020-03 (4.15.0)
macOS 10.14.6 Mojave
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
