### ISSUE TITLE
百度网盘问题解决建议

### ISSUE THREAD

**Issue by mvphp** [AnyListen/tools-ocr#44]
使用国内的Gitee平台进行存放，安全稳定

**Comment by yufengwhy** [comment]
谷歌搜索 树洞ocr  可以找到很多下载地址。比如   [ocr](https://590m.com/dir/7369060-33693673-b63887)

**Comment by mvphp** [comment]
感谢回复！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yufengwhy"<notifications@github.com&gt;; 
发送时间: 2020年7月6日(星期一) 下午4:04
收件人: "AnyListen/tools-ocr"<tools-ocr@noreply.github.com&gt;; 
抄送: "mvphp"<120420871@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AnyListen/tools-ocr] 百度网盘问题解决建议 (#44)





 
谷歌搜索 树洞ocr  可以找到很多下载地址。比如   ocr

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
