### ISSUE TITLE
这个软件做的不如上一个好

### ISSUE THREAD

**Issue by yuanqingshan** [AnyListen/tools-ocr#46]
内容识别失败率很高

**Comment by hjhsjywanan** [comment]
确实，这个用不了，上一个的那个还能用

**Comment by litongjava** [comment]
目前最新版支持多种操作系统，多种芯片。不比上一个版本差

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
