### ISSUE TITLE
跨平台为什么没有Linux下的Release

### ISSUE THREAD

**Issue by jahentao** [AnyListen/tools-ocr#5]
如题

**Comment by AnyListen** [comment]
需要自行编译，目前没有 Linux 机器

**Comment by Coder-21Hertz** [comment]
> 需要自行编译，目前没有Linux机器

想问下这个要怎么编译呢

**Comment by fkxxyz** [comment]
linux下可以直接使用 dmg 包里面编译好的 jar 包，操作如下。
下载 treehole-1.2.0.dmg ，解压出里面的 treehole/treehole.app/Contents/Java 文件夹。
在自己的发行版中用包管理器安装 java 运行环境以及其 openjfx 库（我只试过 java1.8）
然后执行
```
java -jar <路径>/treehole-1.2.0-jfx.jar
```

就可以用了。

---

另外，在 archlinux 里面，我已经写好 PKGBUILD 打包传到了 aur 方便直接使用，可以用 yay 等工具直接安装，包名是 treehole-ocr
```
yay -S treehole-ocr
```

**Comment by vio1etus** [comment]
archlinux 的包可否更新一下？ @fkxxyz

**Comment by litongjava** [comment]
有CentOS的linux但是我没有测试过,请到action下载
https://github.com/litongjava/tools-ocr/actions/runs/6983502464
