### ISSUE TITLE
百度云链接失效了

### ISSUE THREAD

**Issue by kong876** [AnyListen/tools-ocr#52]

**Comment by hikari-He** [comment]
下面有一个老哥分享了一个别的网盘的链接，我给你贴这。不过只有1.2.0版本。
> 谷歌搜索 树洞ocr 可以找到很多下载地址。比如 [ocr](https://590m.com/dir/7369060-33693673-b63887)

**Comment by ShawNova** [comment]
Still

**Comment by nubbhr** [comment]
> 下面有一个老哥分享了一个别的网盘的链接，我给你贴这。不过只有1.2.0版本。
> 
> > 谷歌搜索 树洞ocr 可以找到很多下载地址。比如 [ocr](https://590m.com/dir/7369060-33693673-b63887)

感谢

**Comment by WuZhengqiang666** [comment]
那位老哥是不是 停止更新和维护了。

我看网盘失效且软件好长时间没有更新了。

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
