### ISSUE TITLE
m1 MacBook Pro截图会打开新的空窗口

### ISSUE THREAD

**Issue by pymoni** [AnyListen/tools-ocr#56]
安装的完整版，不带jre运行不了，如题

**Comment by pymoni** [comment]
f4也不能用，不知道是不是要单独配置

**Comment by qizidog** [comment]
同macbook air m1，1.2.1版本有时能用有时不能用，识别效果不稳定。建议增加自定义api接口

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
