### ISSUE TITLE
请问做软件的大佬还在吗

### ISSUE THREAD

**Issue by hmgdd101** [AnyListen/tools-ocr#57]
大佬你还在吗，我一直在用你的天若，树洞我这里装不上，你还在维护这个软件吗

**Comment by mchotdograp** [comment]
我这win10而也是装不上，精简版的1.2.1，提示忘了，反正是很多错误弹窗（已经用管理员打开了）

**Comment by mchotdograp** [comment]
@hmgdd101 安装完整版就可以了
Case closed.
