### ISSUE TITLE
win10一直：正在识别图片，请稍等

### ISSUE THREAD

**Issue by ganfang** [AnyListen/tools-ocr#62]
已经不维护了吗，可惜了。win10专业版的，本机装有jdk17。安装了完整版的1.2.1。截图后回车，一直在‘正在识别图片，请稍等’。上传图片也是

**Comment by Vclimate** [comment]
我也是遇到了这个问题

**Comment by LuxSun** [comment]
+1

**Comment by litongjava** [comment]
问题已解决请重新下载并测试

**Comment by briteming** [comment]
测试了一下。识别程度不高。我一个图片里有2行文字，只识别了第一行
