### ISSUE TITLE
最新版在Windows 10 64位上无法正常运行！

### ISSUE THREAD

**Issue by ScienceZone** [AnyListen/tools-ocr#72]
最新版在Windows 10 64位上无法正常运行！软件刚出来时用过，不大好用，最近用天若OCR时又想到了，下载的压缩包，第一次在其他解压到E盘，内存Read报错，以为下载时出错了，又下载一次在C盘下载目录解压，这次一连出现好几个错误提示，还是无法运行！希望尽快解决无法使用时问题，谢谢！

**Comment by ScienceZone** [comment]
又试了一下，解压地址无中文，有2个错误：Error invoking method、Failed to launch JVM

**Comment by salted-dried-fish** [comment]
遇到了同样的问题，望尽快修复

**Comment by litongjava** [comment]
1.版本号 2.错误截图 3.日志 笔者的日志目录是 D:\dev_program\treehole-v2.2.9-windows-x64-cpu\app\logs 
4.请尝试最新版本

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
