### ISSUE TITLE
需要联网吗？如何设置代理服务器？

### ISSUE THREAD

**Issue by chenglin** [AnyListen/tools-ocr#8]
需要联网吗？如何设置代理服务器？

**Comment by AnyListen** [comment]
目前 OCR 需要联网，代理服务需要等后续设置界面开发完成
这个可能需要等待一段时间

**Comment by laoyam** [comment]
识别的次数 是怎么限制的?

**Comment by AnyListen** [comment]
识别的次数，默认是各个官方API，免费的额度，具体次数没有测试过

**Comment by Chandler-Lu** [comment]
@AnyListen 建议允许用户使用自己申请的API，也省的开发者这边提供API了，稳定性更好一些

**Comment by litongjava** [comment]
最新版本无需联网,完全本地

**Comment by litongjava** [comment]
https://github.com/litongjava/tools-ocr/releases/tag/v2.3.0
