### ISSUE TITLE
多屏时，副屏选取范围没有标识

### ISSUE THREAD

**Issue by XingMingYue** [AnyListen/tools-ocr#9]
https://ws3.sinaimg.cn/large/005BYqpgly1g23azbtmdnj32yo0u0kjm.jpg

**Comment by AnyListen** [comment]
后续添加范围限制

**Comment by AnyListen** [comment]
已修复，请参考：[09b52ad](https://github.com/AnyListen/tools-ocr/commit/09b52adb6f12f49df1e070db75de41584eca5e69)
